#ifndef __CRYPTID_CRYPTID_DEFINES_H
#define __CRYPTID_CRYPTID_DEFINES_H

typedef enum
{
	ABE_CTILDE_SET_NOT_LAST = 0,
	ABE_CTILDE_SET_LAST = 1,
	ABE_CTILDE_SET_NOT_COMPUTED = 2
} CtildeSetState;

#endif
