
#ifndef __CRYPTID_CRYPTID_ENCRYPTEDMESSAGE_AS_BINARY_ABE_H
#define __CRYPTID_CRYPTID_ENCRYPTEDMESSAGE_AS_BINARY_ABE_H

#include "attribute-based/ciphertext-policy/encryption/bsw/BSWCiphertextPolicyAttributeBasedEncryptionEncryptedMessage.h"
#include "attribute-based/ciphertext-policy/encryption/bsw/BSWCiphertextPolicyAttributeBasedEncryptionAccessTreeAsBinary.h"
#include "complex/ComplexAsBinary.h"

typedef struct BSWCiphertextPolicyAttributeBasedEncryptionCtildeSetAsBinary
{
	ComplexAsBinary cTilde;
	struct BSWCiphertextPolicyAttributeBasedEncryptionCtildeSetAsBinary* cTildeSet;
	CtildeSetState last;
} BSWCiphertextPolicyAttributeBasedEncryptionCtildeSetAsBinary;

typedef struct BSWCiphertextPolicyAttributeBasedEncryptionEncryptedMessageAsBinary
{
	BSWCiphertextPolicyAttributeBasedEncryptionAccessTreeAsBinary* tree;
	BSWCiphertextPolicyAttributeBasedEncryptionCtildeSetAsBinary* cTildeSet;
	AffinePointAsBinary c;
} BSWCiphertextPolicyAttributeBasedEncryptionEncryptedMessageAsBinary;

void BSWCiphertextPolicyAttributeBasedEncryptionEncryptedMessageAsBinary_destroy(BSWCiphertextPolicyAttributeBasedEncryptionEncryptedMessageAsBinary* encrypted);

void bswCiphertextPolicyAttributeBasedEncryptionCtildeSetAsBinary_toBswCiphertextPolicyAttributeBasedEncryptionCtildeSet(BSWCiphertextPolicyAttributeBasedEncryptionCtildeSet *ctildeSet, const BSWCiphertextPolicyAttributeBasedEncryptionCtildeSetAsBinary *ctildeSetAsBinary);

void bswCiphertextPolicyAttributeBasedEncryptionCtildeSetAsBinary_fromBswCiphertextPolicyAttributeBasedEncryptionCtildeSet(BSWCiphertextPolicyAttributeBasedEncryptionCtildeSetAsBinary *ctildeSetAsBinary, const BSWCiphertextPolicyAttributeBasedEncryptionCtildeSet *ctildeSet);

void bswChiphertextPolicyAttributeBasedEncryptionEncryptedMessageAsBinary_toBswChiphertextPolicyAttributeBasedEncryptionEncryptedMessage(BSWCiphertextPolicyAttributeBasedEncryptionEncryptedMessage *encryptedMessage, const BSWCiphertextPolicyAttributeBasedEncryptionEncryptedMessageAsBinary *encryptedMessageAsBinary);

void bswChiphertextPolicyAttributeBasedEncryptionEncryptedMessageAsBinary_fromBswChiphertextPolicyAttributeBasedEncryptionEncryptedMessage(BSWCiphertextPolicyAttributeBasedEncryptionEncryptedMessageAsBinary *encryptedMessageAsBinary, const BSWCiphertextPolicyAttributeBasedEncryptionEncryptedMessage *encryptedMessage);

#endif
