#ifndef __CRYPTID_CRYPTID_DEFINES_H
#define __CRYPTID_CRYPTID_DEFINES_H

#define MAX_CHILDREN 128
#define MAX_ATTRIBUTES 128
#define ATTRIBUTE_LENGTH 32

#define ABE_CTILDE_SET_NOT_LAST 0
#define ABE_CTILDE_SET_LAST 1
#define ABE_CTILDE_SET_NOT_COMPUTED 2

#endif
